#!/usr/bin/env tsx
/**
 * Portuguese Law MCP — Census-Driven Ingestion Pipeline
 *
 * Fetches Portuguese legislation from PGDL (pgdlisboa.pt) using the
 * full-text view (ficha=101 parameter) which shows all articles per law.
 *
 * **Census-driven**: Reads data/census.json (generated by scripts/census.ts)
 * to enumerate ALL Portuguese legislation. Falls back to KEY_PORTUGUESE_ACTS
 * if census is missing.
 *
 * Strategy:
 * 1. Load act list from census.json (or fallback to seed list)
 * 2. For each act, fetch the PGDL ficha=101 page (all articles)
 * 3. Convert from ISO-8859-1 to UTF-8
 * 4. Parse articles from the HTML using "Artigo X.º" patterns
 * 5. Write seed JSON files to data/seed/
 *
 * Usage:
 *   npm run ingest                    # Full ingestion (from census)
 *   npm run ingest -- --limit 5       # Test with 5 acts
 *   npm run ingest -- --skip-fetch    # Reuse cached pages
 *   npm run ingest -- --resume        # Skip acts with existing seed files
 *
 * Data is sourced under Portuguese open data terms (PGDL/DRE terms of use).
 */

import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { fetchPgdlFullText } from './lib/fetcher.js';
import { parsePortugueseHtml, KEY_PORTUGUESE_ACTS, type ActIndexEntry, type ParsedAct } from './lib/parser.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SOURCE_DIR = path.resolve(__dirname, '../data/source');
const SEED_DIR = path.resolve(__dirname, '../data/seed');
const CENSUS_PATH = path.resolve(__dirname, '../data/census.json');

interface CensusLaw {
  id: string;
  nid: string;
  title: string;
  citation: string;
  legislationType: string;
  url: string;
  category: string;
  classification: 'ingestable' | 'inaccessible' | 'metadata_only';
}

interface CensusData {
  generated_at: string;
  stats: { total: number; class_ingestable: number; class_inaccessible: number; class_metadata_only: number };
  laws: CensusLaw[];
}

function parseArgs(): { limit: number | null; skipFetch: boolean; resume: boolean } {
  const args = process.argv.slice(2);
  let limit: number | null = null;
  let skipFetch = false;
  let resume = false;

  for (let i = 0; i < args.length; i++) {
    if (args[i] === '--limit' && args[i + 1]) {
      limit = parseInt(args[i + 1], 10);
      i++;
    } else if (args[i] === '--skip-fetch') {
      skipFetch = true;
    } else if (args[i] === '--resume') {
      resume = true;
    }
  }

  return { limit, skipFetch, resume };
}

/**
 * Convert a census law entry into the ActIndexEntry format used by the parser.
 */
function censusLawToActEntry(law: CensusLaw): ActIndexEntry {
  const shortName = law.citation.length > 40
    ? law.citation.substring(0, 37) + '...'
    : (law.citation || law.title.substring(0, 40));

  return {
    id: law.id,
    nid: law.nid,
    title: law.title + (law.citation ? ` — ${law.citation}` : ''),
    titleEn: '',
    shortName,
    citation: law.citation,
    status: 'in_force',
    issuedDate: '',
    inForceDate: '',
    url: law.url,
  };
}

/**
 * Load acts from census.json if available, otherwise fall back to KEY_PORTUGUESE_ACTS.
 */
function loadActList(): ActIndexEntry[] {
  if (fs.existsSync(CENSUS_PATH)) {
    const raw = fs.readFileSync(CENSUS_PATH, 'utf-8');
    const census = JSON.parse(raw) as CensusData;

    console.log(`  Census: ${census.stats.total} laws (generated ${census.generated_at})`);

    // Only include ingestable laws
    const ingestable = census.laws.filter(a => a.classification === 'ingestable');
    console.log(`  Ingestable: ${ingestable.length} laws`);

    return ingestable.map(censusLawToActEntry);
  }

  console.log('  WARNING: No census.json found — falling back to KEY_PORTUGUESE_ACTS');
  console.log('  Run: npx tsx scripts/census.ts   to generate full census\n');
  return KEY_PORTUGUESE_ACTS;
}

async function fetchAndParseActs(acts: ActIndexEntry[], skipFetch: boolean, resume: boolean): Promise<void> {
  console.log(`\nProcessing ${acts.length} Portuguese laws...\n`);

  fs.mkdirSync(SOURCE_DIR, { recursive: true });
  fs.mkdirSync(SEED_DIR, { recursive: true });

  let processed = 0;
  let successful = 0;
  let skipped = 0;
  let resumed = 0;
  let failed = 0;
  let emptyParse = 0;
  let totalProvisions = 0;
  let totalDefinitions = 0;
  const startTime = Date.now();

  const report: { act: string; provisions: number; definitions: number; status: string }[] = [];

  for (const act of acts) {
    const sourceFile = path.join(SOURCE_DIR, `${act.id}.html`);
    const seedFile = path.join(SEED_DIR, `${act.id}.json`);

    // Resume support: skip acts that already have seed files
    if (resume && fs.existsSync(seedFile)) {
      try {
        const existing = JSON.parse(fs.readFileSync(seedFile, 'utf-8')) as ParsedAct;
        totalProvisions += existing.provisions.length;
        totalDefinitions += existing.definitions.length;
      } catch {
        // Ignore invalid JSON — will be re-ingested
      }
      resumed++;
      processed++;
      continue;
    }

    // Skip if seed already exists and we're in skip-fetch mode
    if (skipFetch && fs.existsSync(seedFile)) {
      try {
        const existing = JSON.parse(fs.readFileSync(seedFile, 'utf-8')) as ParsedAct;
        report.push({
          act: act.shortName,
          provisions: existing.provisions.length,
          definitions: existing.definitions.length,
          status: 'cached',
        });
        totalProvisions += existing.provisions.length;
        totalDefinitions += existing.definitions.length;
      } catch {
        report.push({ act: act.shortName, provisions: 0, definitions: 0, status: 'bad cache' });
      }
      skipped++;
      processed++;
      continue;
    }

    try {
      let html: string;

      if (fs.existsSync(sourceFile) && skipFetch) {
        html = fs.readFileSync(sourceFile, 'utf-8');
        console.log(`  Using cached ${act.shortName} (nid=${act.nid})`);
      } else {
        process.stdout.write(`  [${processed + 1}/${acts.length}] Fetching nid=${act.nid} (${act.shortName})...`);

        const result = await fetchPgdlFullText(act.nid);
        if (!result || result.status !== 200) {
          console.log(` HTTP ${result?.status ?? 'no response'} — SKIPPED`);
          report.push({ act: act.shortName, provisions: 0, definitions: 0, status: `HTTP ${result?.status ?? 'err'}` });
          failed++;
          processed++;
          continue;
        }

        // PGDL encoding is handled by the fetcher (latin1 -> UTF-8)
        html = result.body;

        // Check for error pages / empty content
        if (html.length < 1000 || (html.includes('Erro') && html.includes('registo'))) {
          console.log(` empty/error page — SKIPPED`);
          report.push({ act: act.shortName, provisions: 0, definitions: 0, status: 'empty page' });
          failed++;
          processed++;
          continue;
        }

        fs.writeFileSync(sourceFile, html);
        console.log(` OK (${(html.length / 1024).toFixed(0)} KB)`);
      }

      const parsed = parsePortugueseHtml(html, act);

      // If zero provisions parsed, still save as metadata-only
      if (parsed.provisions.length === 0) {
        emptyParse++;
        report.push({ act: act.shortName, provisions: 0, definitions: 0, status: 'no articles' });
      } else {
        report.push({
          act: act.shortName,
          provisions: parsed.provisions.length,
          definitions: parsed.definitions.length,
          status: 'OK',
        });
      }

      fs.writeFileSync(seedFile, JSON.stringify(parsed, null, 2));

      totalProvisions += parsed.provisions.length;
      totalDefinitions += parsed.definitions.length;
      successful++;

      if (parsed.provisions.length > 0) {
        console.log(`    -> ${parsed.provisions.length} provisions, ${parsed.definitions.length} definitions`);
      }
    } catch (error) {
      const msg = error instanceof Error ? error.message : String(error);
      console.log(`  ERROR parsing ${act.shortName}: ${msg}`);
      report.push({ act: act.shortName, provisions: 0, definitions: 0, status: `ERROR: ${msg.substring(0, 80)}` });
      failed++;
    }

    processed++;

    // Progress log every 50 acts
    if (processed % 50 === 0) {
      const elapsed = ((Date.now() - startTime) / 1000).toFixed(0);
      const eta = ((Date.now() - startTime) / processed * (acts.length - processed) / 1000).toFixed(0);
      console.log(`\n  --- Progress: ${processed}/${acts.length} (${elapsed}s elapsed, ~${eta}s remaining, ${totalProvisions} provisions so far) ---\n`);
    }
  }

  const totalElapsed = ((Date.now() - startTime) / 1000).toFixed(1);

  // Print summary report
  console.log(`\n${'='.repeat(72)}`);
  console.log('INGESTION REPORT');
  console.log('='.repeat(72));

  if (report.length <= 100) {
    console.log(`${'Act'.padEnd(42)} ${'Prov'.padEnd(8)} ${'Defs'.padEnd(8)} Status`);
    console.log('-'.repeat(72));
    for (const r of report) {
      console.log(
        `${r.act.substring(0, 41).padEnd(42)} ${String(r.provisions).padEnd(8)} ${String(r.definitions).padEnd(8)} ${r.status}`
      );
    }
    console.log('-'.repeat(72));
  } else {
    // For large runs, show aggregated stats
    const okCount = report.filter(r => r.status === 'OK').length;
    const failedCount = report.filter(r => !['OK', 'cached', 'no articles'].includes(r.status)).length;
    const cachedCount = report.filter(r => r.status === 'cached').length;
    const noArticleCount = report.filter(r => r.status === 'no articles').length;
    console.log(`  Successful:      ${okCount}`);
    console.log(`  Cached:          ${cachedCount}`);
    console.log(`  No articles:     ${noArticleCount}`);
    console.log(`  Failed:          ${failedCount}`);
    if (failedCount > 0 && failedCount <= 50) {
      console.log('\n  Failed/error laws:');
      for (const r of report.filter(r => !['OK', 'cached', 'no articles'].includes(r.status))) {
        console.log(`    ${r.act.substring(0, 41).padEnd(42)} ${r.status}`);
      }
    }
  }

  console.log(`\n${'='.repeat(72)}`);
  console.log(`  Total elapsed:     ${totalElapsed}s`);
  console.log(`  Laws processed:    ${processed}`);
  console.log(`  Laws successful:   ${successful}`);
  console.log(`  Laws resumed:      ${resumed}`);
  console.log(`  Laws cached:       ${skipped}`);
  console.log(`  Laws failed:       ${failed}`);
  console.log(`  Empty parses:      ${emptyParse}`);
  console.log(`  Total provisions:  ${totalProvisions}`);
  console.log(`  Total definitions: ${totalDefinitions}`);

  // Update census.json with ingestion stats
  if (fs.existsSync(CENSUS_PATH)) {
    const census = JSON.parse(fs.readFileSync(CENSUS_PATH, 'utf-8'));
    census.ingestion = {
      completed_at: new Date().toISOString(),
      total_laws: successful + resumed + skipped,
      total_provisions: totalProvisions,
      coverage_pct: ((successful + resumed + skipped) / acts.length * 100).toFixed(1),
    };

    // Update classification for failed laws
    if (failed > 0) {
      const failedNames = new Set(
        report.filter(r => !['OK', 'cached', 'no articles'].includes(r.status)).map(r => r.act)
      );
      for (const law of census.laws) {
        if (failedNames.has(law.citation) || failedNames.has(law.title)) {
          law.classification = 'inaccessible';
        }
      }
      census.stats.class_ingestable = census.laws.filter((a: CensusLaw) => a.classification === 'ingestable').length;
      census.stats.class_inaccessible = census.laws.filter((a: CensusLaw) => a.classification === 'inaccessible').length;
    }

    fs.writeFileSync(CENSUS_PATH, JSON.stringify(census, null, 2) + '\n');
    console.log(`\n  Updated census.json with ingestion stats.`);
  }
}

async function main(): Promise<void> {
  const { limit, skipFetch, resume } = parseArgs();

  console.log('Portuguese Law MCP — Ingestion Pipeline');
  console.log('========================================\n');
  console.log(`  Source:  PGDL (pgdlisboa.pt) — full-text view (ficha=101)`);
  console.log(`  Method:  Fetch all articles -> parse Artigo X.º -> write seeds`);
  console.log(`  License: Portuguese Open Data (attribution required)`);

  if (limit) console.log(`  --limit ${limit}`);
  if (skipFetch) console.log(`  --skip-fetch`);
  if (resume) console.log(`  --resume (skip existing seed files)`);

  const allActs = loadActList();
  const acts = limit ? allActs.slice(0, limit) : allActs;
  await fetchAndParseActs(acts, skipFetch, resume);
}

main().catch(error => {
  console.error('Fatal error:', error);
  process.exit(1);
});
